# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170908_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='static/home/images/db_images'),
        ),
    ]
