# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170908_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
